### ISSUE TITLE
Gender deprecated with NabuCasea removed

### ISSUE THREAD

**Issue by joohann** [nimroddolev/chime_tts#106]
### System Health details

![Screenshot 2024-04-06 at 01 25 38](https://github.com/nimroddolev/chime_tts/assets/5968403/d49f6e6f-80ec-46ed-9a08-8f6a7db2a5e3)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

![Screenshot 2024-04-06 at 01 31 10](https://github.com/nimroddolev/chime_tts/assets/5968403/61680dea-3339-448d-9d54-1abb284fda1f)
config needs to be updated.
Change gender by voice.

### Reproduction steps

Also when using developer tools it's not working with gender

### Debug logs

```text
It's in the update
```

**Comment by nimroddolev** [comment]
Thanks @joohann.

I just released a new beta which replaces the deprecated `gender` parameter with `voice`.
I'd appreciate it if you could please install the new version and let me know if it's working for you, as well as any other feedback you might have.

To install the new beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option (it may take a moment to update the list)
1. Select version `v1.0.1-beta1` from the updated version drop-down list
1. Restart Home Assistant

**Comment by joohann** [comment]
Keep you posted 😊

**Comment by joohann** [comment]
No more errors anymore  but I'm not able to get a male voice.

**Comment by nimroddolev** [comment]
To use a male voice you simply need to specify a male voice from the [list of voices](https://github.com/NabuCasa/hass-nabucasa/blob/390fff2e154de479f8283f010a47729fba205380/hass_nabucasa/voice.py#L50-L801), eg: `BrandonNeural`.

**Comment by nimroddolev** [comment]
You really shouldn't. The voices aren't documented anywhere. I had the same issue.
