### ISSUE TITLE
Dropdown for chimes has "Custom 5" listed twice instead of "Custom 4" and then "Custom 5"

### ISSUE THREAD

**Issue by dimatx** [nimroddolev/chime_tts#120]
### System Health details

Using v1.1.0-beta4, but this was also true on prior versions.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The dropdown for chime path has "5" listed twice instead of "4" and then "5"

![image](https://github.com/nimroddolev/chime_tts/assets/24803941/5e06fedc-7741-45ae-ac39-24e3c6cda19e)

### Reproduction steps

1. Setup Chime TTS
2. Click on dropdown for Chime Path

### Debug logs

```text
n/a
```

**Comment by nimroddolev** [comment]
Hi @dimatx.

Thank you for raising the issue 👍 

I have added a fix to v1.1.0-beta5

To install the new beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option (it may take a moment to update the list)
1. Select version `v1.1.0-beta5` from the updated version drop-down list
1. Restart Home Assistant

**Comment by dimatx** [comment]
Confirmed fixed. Thanks!
