### ISSUE TITLE
Unable to create public URL

### ISSUE THREAD

**Issue by Whizzykid** [nimroddolev/chime_tts#124]
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4299
Installed Version | 1.34.0
Stage | running
Available Repositories | 1408
Downloaded Repositories | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 26, 2024 at 12:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-8.ui.nabu.casa
certificate_status | ready
instance_id | 325dff22b7c24b0e8a0d85afec092ecd
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | beta
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 457.7 GB
disk_used | 21.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Advanced SSH & Web Terminal (17.2.0), deCONZ (6.23.0), Filebrowser (2.23.0_14), PS5 MQTT (1.3.3), RTSP Simple Server Add-on (v0.17.6), eufy-security-ws (1.8.0), Mosquitto broker (6.4.0), flicd (2.0.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 27
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 21, 2024 at 7:49 AM
-- | --
current_recorder_run | April 28, 2024 at 6:36 PM
estimated_db_size | 906.81 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Suddenly I can no longer get Alexa to say the chimes. The log shows an error like so :

Unable to create public URL - File: '/www/chime_tts/1zco0z49.mp3' is outside the public folder

Could somebody please help? I've not made any changes to the add on or my HA which would have led to this

Running the service on devices that are not Alexa seem to work fine

### Reproduction steps

1. Trying to run the Chime TSS: Say service to any Alexa device
3.
4.
...

### Debug logs

```text
.
```

**Comment by nimroddolev** [comment]
It looks like the folder path you have set for the `chime_tts.say_url` service in the Chime TTS integration configuration page is missing the initial`/config` folder.

Try changing it to:
```
/config/www/chime_tts
```

**Comment by nimroddolev** [comment]
@Whizzykid is this issue still still relevant?

**Comment by Whizzykid** [comment]
I believe it fixed itself! You can close

**Comment by nimroddolev** [comment]
Thank you
