### ISSUE TITLE
Link is broken for intergration

### ISSUE THREAD

**Issue by xenovia** [nimroddolev/chime_tts#127]
### System Health details

Link is broken for intergration

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Link is broken for intergration

### Reproduction steps

1.
2.
3.
...
Link is broken for intergration

### Debug logs

```text
Link is broken for intergration
```

### Diagnostics dump

Link is broken for intergration

**Comment by nimroddolev** [comment]
Which link are you referring to?

**Comment by xenovia** [comment]
Quick Start
Follow these easy steps to get started with Chime TTS:

[Installation](https://github.com/nimroddolev/chime_tts/wiki/Installation) - Quickly install Chime TTS via HACS or manually.
[Add the Integration](https://github.com/nimroddolev/chime_tts/%5Bwiki/Installation#2%5D(https://github.com/wiki/Installation/issues/2)-add-the-chime-tts-integration) - Add Chime TTS to your Home Assistant instance.

**Comment by nimroddolev** [comment]
Thanks. Could you also please provide the URL to the page which has the incorrect link?
