### ISSUE TITLE
OpenAI TTS API Key

### ISSUE THREAD

**Issue by Steveelliott111** [nimroddolev/chime_tts#140]
### System Health details

Couldnt find the health card

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

OpenAI TTS Key - There is no documentation to advise where this needs to be put. I've tried putting it int he configuration.yaml file and sleect OpenAI TTS from the service. But the voices dont play.

### Reproduction steps

1.
as aboe
2.
3.
...

### Debug logs

```text
na
```

**Comment by nimroddolev** [comment]
Hi @Steveelliott111.

The OpenAI TTS integration is entirely separate to the Chime TTS integration. Please review the [integration's GitHub repository](https://github.com/sfortis/openai_tts) for the steps to install and configure it.
