### ISSUE TITLE
not working if template containes round or int or the likes

### ISSUE THREAD

**Issue by scargill** [nimroddolev/chime_tts#147]
## System Information

version | core-2024.6.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28+rpt-rpi-2712
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4976
Installed Version | 1.34.0
Stage | running
Available Repositories | 1400
Downloaded Repositories | 24
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 7 July 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-19.ui.nabu.casa
certificate_status | ready
instance_id | e61c5da28bdf4c3cb8c0fc346b780f95
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 June 2024 at 02:12
-- | --
current_recorder_run | 16 June 2024 at 18:04
estimated_db_size | 306.66 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 7 / 42
local_online | 2 / 2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

i have this script, it worked for days, but now on 1.1.0beta15 and ha 2024.6.2 it does not work anymore (or works partially, i can hear just music but no tts, or viceversa) unless i remove all the |round in the template

```
alias: ironman
sequence:
  - service: chime_tts.say
    data_template:
      chime_path: /media/ironman.mp3
      tts_platform: tts.google_en.com
      message: >-
        Hi Pete! The time is {{ now().strftime('%H %M') }}. The forcast says the
        temperature is currently {{ state_attr('weather.forecast_home',
        'temperature')|round }} and the humidity is {{
        state_attr('weather.forecast_home','humidity')|round }} %. Wind speed is
        {{ state_attr('weather.forecast_home','wind_speed')|round }} kilometers
        an hour.
      offset: -39000
      tts_speed: 125
      tts_pitch: 0
    target:
      device_id: a5ea741b4a3f91d6bcbb273ecd84f1ef
description: ""
```

### Reproduction steps

as above stated

### Debug logs

```text
nothing there
```

**Comment by fragolinux** [comment]
same here

**Comment by dbullendsl** [comment]
Not a problem for me, works just fine changing the script to my weather provider.  I also have a much longer message script that uses the round function and is working just fine on Beta 15

**Comment by nimroddolev** [comment]
Hi @scargill and @fragolinux. I'm sorry you've been having this issue.

I've been able to reproduce the bug and i've patched the it. It will be made available in the next release.

**Comment by nimroddolev** [comment]
Can you please upgrade to the latest stable release, v1.1.0, and let me know if the issue is resolved for you?

**Comment by scargill** [comment]
Soon as I get home this afternoon I'll report back. Thanks for updating. I should find a way to play this on my Samsung phone so I can test on the road 😁😁😁

**Comment by lionslair** [comment]
I have variables in my messages. The automations playing chime tss with variables are not working. Do not even get the l bells chime before the message. Nothing in logs. Home assistant seems to think all ran normally but nothing gets played. 

Disabled the action and made another chimetss action with no variables. Also didn't play when tested.

Does this sound like any relation to this?

Odd thing is when the garage door opens or closes that message plays fine. Is no variables in those actions though.

**Comment by lionslair** [comment]
Ah ok after more playing around and things I think I solved it. Working again
 I just had to go into the integration reconfigure. Save the configuration again and they then I get them playing again. Sorry. I messed around last night and this morning but was drawing blanks. 

Maybe from the update I had to save configuration for the integration again

**Comment by nimroddolev** [comment]
I’m happy you were able to resolve it. Feel free to reopen this issue if you experience it again.
