### ISSUE TITLE
chime_tts.say_url "...does not support 'response_variable'..."

### ISSUE THREAD

**Issue by DarkFox** [nimroddolev/chime_tts#149]
## System Information

version | core-2024.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4921
Installed Version | 1.34.0
Stage | running
Available Repositories | 1410
Downloaded Repositories | 83
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 17. august 2024 kl. 02.00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-9.ui.nabu.casa
certificate_status | ready
instance_id | 2d59c8bc577a4f96b63751f88b91ebfd
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 229.4 GB
disk_used | 95.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), Custom deps deployment (1.3.4), Nginx Proxy (0.1.14), Certbot (0.1.10), deCONZ (6.23.0), Advanced SSH & Web Terminal (18.0.0), Z-Wave JS UI (3.8.0), MariaDB (2.7.1), Studio Code Server (5.15.0), ESPHome (2024.6.1), Tailscale with features (0.20.0.1), Portainer (2.20.1), phpMyAdmin (0.9.1), Whisper (2.1.0), Piper (1.5.0), Dropback (7.3.1), Firefox (1.2.0), Castsponsorskip (0.7.4), Radarr (5.6.0.8846), Sonarr (4.0.5.1740), Overseerr (1.33.2), Prowlarr NAS (nightly-1.19.0.4557-ls216), Transmission Openvpn (v5.3.1-6), Plex NAS (1.40.3.8555-fef15d30c-ls219), Cloudcommander (17.4.1), Bazarr NAS (1.4.3), Booksonic-air (2201.1.0), FlareSolverr (3.3.19), Music Assistant BETA (2.1.0b7), tubesync (v0.13.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 20
-- | --
resources | 52
views | 34
error | /config/lovelace-bathroom-mirror.yaml not found
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24. marts 2024 kl. 12.29
-- | --
current_recorder_run | 21. juni 2024 kl. 12.32
estimated_db_size | 14516.09 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The chime_tts.say_url  has stopped working with the error `Script does not support 'response_variable' for service 'response_variable' which does not support response data.`.

### Reproduction steps

1. Call the chime_tts.say_url using
      ```yaml
      service: chime_tts.say_url
      response_variable: tts_url
      data:
        message: Test message
        tts_platform: cloud
      ```
2. Observe that the call fails.

### Debug logs

```text
2024-06-21 12:34:21.225 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: Script does not support 'response_variable' for service 'response_variable' which does not support response data.
2024-06-21 12:34:21.226 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140268681384512] Error handling message: Script does not support 'response_variable' for service 'response_variable' which does not support response data.. Got {'type': 'execute_script', 'sequence': [{'service': 'chime_tts.say_url', 'response_variable': 'tts_url', 'data': {'message': 'Test message', 'tts_platform': 'cloud'}}], 'id': 121} (invalid_format) Martin from 100.97.252.15 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0)
```

**Comment by nimroddolev** [comment]
Hi @DarkFox, thank you for raising the issue.

I have fixed the bug and released the fix in v1.1.1
