### ISSUE TITLE
Error "No TTS platforms were detected" when saving any configuration

### ISSUE THREAD

**Issue by Steedius** [nimroddolev/chime_tts#150]
## System Information

version | core-2024.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1386
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 3, 2025 at 8:00 PM
relayer_connected | true
relayer_region | x
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | x
certificate_status | ready
instance_id | x
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 28.0 GB
disk_used | 5.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | green
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (6.1.2), File editor (5.8.0), Terminal & SSH (9.14.0), Let's Encrypt (5.0.21)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 2
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 11, 2024 at 4:30 PM
-- | --
current_recorder_run | June 21, 2024 at 3:40 PM
estimated_db_size | 130.74 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When attempting to save any config (even if it was the default values), I receive the following error:

> No TTS platforms were detected. Please add at least 1 TTS integration.

Sadly the debug logs won't be much help but I included them. It looks like it _could_ be an issue with an empty configuration object or something? 

This bug very well could have existed for me before the 1.1.1 update. I just needed to increase the timeout today and happen to encounter this error.

### Reproduction steps

1. Open integration config for ChimeTTS
2. Change any value (or don't change any at all) 
3. Hit submit

### Debug logs

```text
2024-06-21 15:41:55.309 DEBUG (MainThread) [custom_components.chime_tts.config_flow] -----  Chime TTS Version v1.1.1 Configuration -----
2024-06-21 15:42:25.383 DEBUG (MainThread) [custom_components.chime_tts.config_flow] -----  Chime TTS Version v1.1.1 Configuration -----
```

**Comment by nimroddolev** [comment]
Thanks for opening the issue @Steedius.
I fixed the bug and released it in v1.1.2

**Comment by Steedius** [comment]
That did it! Just confirmed I can save the integration config now, thank you!

**Comment by nimroddolev** [comment]
Excellent!
Thanks again for opening the issue 👍
