### ISSUE TITLE
Latest Update ignores volume setting when announce is set true

### ISSUE THREAD

**Issue by andyfrei** [nimroddolev/chime_tts#154]
## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Zurich
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1386
Downloaded Repositories | 67

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 469.4 GB
disk_used | 37.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0), InfluxDB (5.0.0), Grafana (10.0.0), Samba share (12.3.1), ESPHome (2024.6.1), Mosquitto broker (6.4.1), AirSonos (4.2.1), RTSPtoWeb - WebRTC (1.4.0), UniFi Network Application (3.1.0), ESPresense Companion (0.6.5), MQTT Explorer (browser-1.0.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 46
views | 73
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10. Juni 2024 um 18:15
-- | --
current_recorder_run | 23. Juni 2024 um 08:53
estimated_db_size | 826.40 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

With the latest update, when announce is set to true and no volume specified (because already handled elsewhere) chime does ignore the current set volume level of the speaker(s) and just "screams" at 100%.

### Reproduction steps

1. call service chime_tts_say: send message with announce false and NO volume level specified
> volume level used is the one which is set on the player at that time
2. call service chime_tts_say: send message with announce true and NO volume level specified
> volume level currently set gets ignored and announcement gets sent with 100%

### Debug logs

```text
see diagnostics dump
```

### Diagnostics dump

[home-assistant_chime_tts_2024-06-23T08-44-47.060Z.log](https://github.com/user-attachments/files/15943906/home-assistant_chime_tts_2024-06-23T08-44-47.060Z.log)

**Comment by nimroddolev** [comment]
Hi @andyfrei. I'm sorry you've run into this issue and thank you for providing the debug log messages.

I believe I have found and fixed the bug, but seeing as I do not own any Sonos speakers I am unable to verify the fix on actual hardware.

Could you please upgrade to v1.1.4-beta1, and let me know if the issue is resolved for you?

To install the beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>.
1. Click on the `⋮` button in the top right.
1. Select the `↻ Redownload` option.
1. Enable the `Show beta versions` option (it may take a moment to update the list).
1. Select version `v1.1.4-beta1` from the updated version drop-down list.
1. Restart Home Assistant.

**Comment by andyfrei** [comment]
Hi nimroddev

 

Yes, I can confirm that with v1.1.4-beta1 this issue is fixed. Great work!!!

Cheers

**Comment by nimroddolev** [comment]
Glad to hear it! 👍
