### ISSUE TITLE
Duplicate keys for cache options in clear_cache services.yaml

### ISSUE THREAD

**Issue by gdgib** [nimroddolev/chime_tts#177]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

https://github.com/nimroddolev/chime_tts/blob/main/custom_components/chime_tts/services.yaml#L13 and https://github.com/nimroddolev/chime_tts/blob/main/custom_components/chime_tts/services.yaml#L39 have the same key, and are almost identical.

This was introduced in https://github.com/nimroddolev/chime_tts/commit/77ae85ad43b02e97320c62d0968de0d3e1c07907#diff-fe4ec1ac4b861db56792ba5b0e27b95abe4a6b7d4ec5c5a796854499012ef5a8

I'm not sure how you would prefer to resolve it, since they're *almost* identical.

### Reproduction steps

1. Run 1.1.4-beta4
2. Examine the HA core logs

### Debug logs

```text
N/A
```

**Comment by gdgib** [comment]
Don't get me wrong if you REALLY want debug logs for this I will, but since I provided links to the exact lines of yaml that aren't correct, I figured you probably didn't need much more.  Apologies if I'm wrong, and thanks for all the hard work!

**Comment by nimroddolev** [comment]
Hi @gdgib, thanks for opening this issue. I have already fixed this bug in one of the beta versions.
I will close this issue once the fix is available in a stable release.

**Comment by nimroddolev** [comment]
Hi @gdgib. I fixed this issue in v1.1.5.
Can you please verify that it's working for you?

**Comment by gdgib** [comment]
Oh sorry!  Yeah, this looks good to me.

**Comment by gdgib** [comment]
Thank you so much!
