### ISSUE TITLE
Setting the voice only works if also setting the language

### ISSUE THREAD

**Issue by SixFive7** [nimroddolev/chime_tts#179]
## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.99-Unraid
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4933
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 4
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 23, 2025 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-3.ui.nabu.casa
certificate_status | ready
instance_id | d4937bdc12f84cb89c3124f867daa228
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 1
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 8, 2024 at 02:02
-- | --
current_recorder_run | August 13, 2024 at 19:01
estimated_db_size | 149.69 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

If you do not set the language to `nl-NL` (even though that is my default), but do set the voice to `MaartenNeural`. You get this error when running the action:
![image](https://github.com/user-attachments/assets/be4ddbc4-05a0-4b88-8fac-e2839066329a)

I also tried this on `v1.1.4-beta4`. Same result.
Setting any language fixes the issue.

This is my entire config:
![image](https://github.com/user-attachments/assets/b37e3a8f-148e-4afe-9389-49bf3b671170)

### Reproduction steps

1. Create the action.
2. Test run the action.
3. See error.

### Debug logs

```text
Not relevant.
```

**Comment by nimroddolev** [comment]
Hi @SixFive7. Please update to the latest stable release, v1.1.4, where I have a fix that addresses this issue.

I am closing this issue, but please reopen it if you still experience the issue after updating.
