### ISSUE TITLE
Specify name of MP3 output file

### ISSUE THREAD

**Issue by cregeland** [nimroddolev/chime_tts#185]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Trying to get ChimeTTS output to play on LMS server using LMSannounce plugin

### Describe the solution you'd like

Is is possible to specify the name of the mp3 file generated? 

Use case:
- Lyrion Music Server with Announce plugin to allow for a mp3 file or playlist to be played - then resume music playing before announcement was played
- I generate the TTS from HA using chimeTTS. If I could specify the name of the mp3 file I can have a fixed playlist in LMS referencing 1 mp3 file (i.e "tts-announcement.mp3") and only generate/overwrite the mp3 with different content.

There might be a better way to handle this. The LMS plugin for announcement is triggered by sending this command to play a local playlist: `http://lmsserver:9000/plugins/LMSannounce/js.html?cmd=announcePlaylist&playlist=somepls&playerid=00%3A00%3A00%3A00%3A00%3A00`

or by this command to play a specific file:

`http://lmsserver:9000/plugins/LMSannounce/js.html?cmd=announceFile&file=%2Fdata%2Fmusic%2Fsoundeffects%2Fring.mp3&playerid=00%3A00%3A00%3A00%3A00%3A00`

I am using shell commands in HA to send these commands:
`play_notify_stue: 'curl -G "http://192.168.1.20:9000/plugins/LMSannounce/js.html" --data-urlencode "cmd=announcePlaylist" --data-urlencode "playlist=nameofplaylist" --data-urlencode "playerid=00:05:30:18:35:3e"'`

Maybe a different approach would be to include the generated name of the mp3 file directly in the shell command - instead of using playlist.

Commands accepted by LMSannounce plugin: https://nexus0.net/pub/sw/lmsannounce/

Thank you :)

### Describe alternatives you've considered

Using ChimeTTS to play directly to the speaker would be best - but that does not allow for resuming playback after announcement completed.

**Comment by nimroddolev** [comment]
Hi @cregeland,

Thank you for the feature request, however I believe you can already achieve this with the current implementation of Chime TTS.

Seeing as you are able to supply Lyrion with the filepath to an MP3 file, you should be able to use the `chime_tts.say_url` action, which returns a dictionary object that includes a `url` key whose value is the file path to the generated MP3 file output from Chime TTS.

**Comment by nimroddolev** [comment]
I am closing this issue, but please reopen it if the my solution is unacceptable.
