### ISSUE TITLE
Configuration screen fields are mandatory and don't use the default values from documentation

### ISSUE THREAD

**Issue by dougmaitelli** [nimroddolev/chime_tts#190]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

According to the documentation on the website the fields available in the Configuration screen have default values, but if you try to edit the configuration all of these fields are blank by default and are mandatory.

### Describe the solution you'd like

It should be possible to override just some of them and leave the others blank so the integration use the default values mentioned in the documentation.

### Describe alternatives you've considered

It would at least be nice if the fields would display their default values.

**Comment by nimroddolev** [comment]
Hi @dougmaitelli, I just released the fix in v1.1.5-beta1. Can you please upgrade to the new [beta version](https://nimroddolev.github.io/chime_tts/docs/quick-start/installing-chime-tts#beta-versions) and let me know if the issue is now resolved for you?

**Comment by nimroddolev** [comment]
Great! Thank you for confirming 👍
