### ISSUE TITLE
How to setup with my custom mp3 as background sound?

### ISSUE THREAD

**Issue by JackieLiu123** [nimroddolev/chime_tts#196]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have downloaded the mp3 audio in my folder. But I cant make the program find this audio successfully. I think maybe both the folder and the yaml I have written are wrong QAQ. However, there is no any example for this. So could you please give me some example?Tks.

### Describe the solution you'd like

One example about the folder my mp3 audio should be in and the yaml I should write

### Describe alternatives you've considered

I even change the source code.But when the project upgrade, it needs me to rewrite.So I come here for some solution.

**Comment by nimroddolev** [comment]
Hi @JackieLiu123.

I suggest you review the [documentation for Chime TTS](https://nimroddolev.github.io/chime_tts), which has explanations for [configuring](https://nimroddolev.github.io/chime_tts/docs/documentation/configuration) and usage [examples](https://nimroddolev.github.io/chime_tts/docs/documentation/actions/say-action/examples).

If you are still having issues, please share the YAML you are using to call the `chime_tts.say` / `chime_tts.say_url` actions, and your [debug log messages](https://nimroddolev.github.io/chime_tts/docs/support#debug-logging) to help me understand what the issue might be.

**Comment by JackieLiu123** [comment]
Thank you so much, I will read them and have a try!
