### ISSUE TITLE
MEDIA_TYPE_MUSIC - depricated constant in HA Core 2025.10 - use MediaType.MUSIC instead

### ISSUE THREAD

**Issue by chris4prez** [nimroddolev/chime_tts#198]
### System Health details

Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:197
integration: Media player ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 5:05:04 PM (1 occurrences)
Last logged: 5:05:04 PM
MEDIA_TYPE_MUSIC was used from chime_tts, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.MUSIC instead, please report it to the author of the 'chime_tts' custom integration

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

MEDIA_TYPE_MUSIC was used from chime_tts, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.MUSIC instead.

### Reproduction steps

1. Use ChimeTTS via 2025.10
2.
3.
...

### Debug logs

```text
Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:197
integration: Media player ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 5:05:04 PM (1 occurrences)
Last logged: 5:05:04 PM
MEDIA_TYPE_MUSIC was used from chime_tts, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.MUSIC instead, please report it to the author of the 'chime_tts' custom integration
```

**Comment by velodromen** [comment]
Same issue here.

**Comment by nimroddolev** [comment]
Thank you. The newer `MediaType.MUSIC` will be used instead of the deprecated `MEDIA_TYPE_MUSIC` constant in the next release.

**Comment by velodromen** [comment]
Great, thank you!
________________________________
Från: Nimrod Dolev ***@***.***>
Skickat: den 17 oktober 2024 20:33
Till: nimroddolev/chime_tts ***@***.***>
Kopia: velodromen ***@***.***>; Comment ***@***.***>
Ämne: Re: [nimroddolev/chime_tts] MEDIA_TYPE_MUSIC - depricated constant in HA Core 2025.10 - use MediaType.MUSIC instead (Issue #198)


Thank you. The newer MediaType.MUSIC will be used instead of the deprecated MEDIA_TYPE_MUSIC constant in the next release.

**Comment by nimroddolev** [comment]
I just released a new beta version, v1.1.6-beta1, which addresses the issue. Can you please [upgrade to the beta version](https://nimroddolev.github.io/chime_tts/docs/quick-start/installing-chime-tts#beta-versions) and let me know if you're still experiencing the issue?

**Comment by velodromen** [comment]
The beta version appear to have resolved the issue.Will let you know in case I experience the issue again. Thanks for the quick fix!

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Moonbase59** [comment]
Also experiencing this, thanks for taking care of it!

**Comment by nimroddolev** [comment]
> Also experiencing this, thanks for taking care of it!

Are you experiencing this with the latest beta version?

**Comment by ruyterpde** [comment]
Running HASS Agent version 2.1.1:

MEDIA_TYPE_MUSIC was used from hass_agent, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.MUSIC instead, please report it to the author of the 'hass_agent' custom integration

![Image](https://github.com/user-attachments/assets/050db761-543c-4c85-a6cd-d1fd2abc7a7e)
