### ISSUE TITLE
Make video with chime and tts from a camera snapshot for Nest Hub

### ISSUE THREAD

**Issue by PilaScat** [nimroddolev/chime_tts#201]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I want to see the doorbeel camera when someone click it.

### Describe the solution you'd like

Making a video with a static image from a snapshot I already have should be simple

### Describe alternatives you've considered

Custom automation but is not perfect

### Additional context

Should be compatible with Nest, 1080p h264

**Comment by nimroddolev** [comment]
Hi @PilaScat. I don’t understand what you are tying to do and what you expect Chime TTS to do to as part of the solution.
Can you please explain more broadly what you are trying to accomplish?

**Comment by PilaScat** [comment]
Hi, I want to send an announce to my Nest Hub with a chime, a testa message, and an image from my camera, now I use chime tts to do the first part, the I wait some seconds and send the image manually, but if I could send a videowoth a static image and chime and tts as audio would be perfect

**Comment by nimroddolev** [comment]
I think it’s beyond the scope of Chime TTS.

You can achieve this with FFmpeg though, supplying the still image path from the camera and the audio file path from the `url` key value from the [`chime_tts.say_url`](https://nimroddolev.github.io/chime_tts/docs/documentation/actions/say_url-action/) response object.
