### ISSUE TITLE
Select relevant Media Player to receive the TTS command dynamically

### ISSUE THREAD

**Issue by andyfrei** [nimroddolev/chime_tts#205]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would like to select player dynamically according to different states of other sensors/templates/booleans. Please see "additional context for more infos why.

### Describe the solution you'd like

I would like to be able to determine if a player needs to play the TTS and bundle the relevant ones into one chime_tts.say command. Bonus: Different volume levels per player would be "the cream" but can be solved in a different way (and in my case is already).

### Describe alternatives you've considered

I've tried to do that with a jinja file and refer to that result in the chime_tts.say. That seems to work somehow but very unreliable (and changes quite alot due to changes of HASS, Sonos, whatever I don't know...
I've also tried to send the Chime_tts.say to each player separately if applicable (in a parallel command within a script). That ends up beeing not synchronized (of course) and most of the time TTS shouts out after each other leading to echoing the TTS severall times and makes it therefor annoying but at least reliable.

### Additional context

Following setup:
a) A house with different floors and different rooms. Not all of them have a Sonos Media Player. Lets say there is nobody in the second floor, then it makes no sense to make them players play the TTS, so I want to make them only active if someone is present in that level.
b) Lets say in the first floor there is a speaker in the entrance and one in the kitchen. When someone is present in the kitchen I would like to send the TTS command to that player in the kitchen with normal volume level (and announce: true). But since there is also someone else in the office in the first floor (with no speaker) I would like to send the TTS to the entrance aswell but with louder volume so that person can hear the TTS aswell.
c) The third player in another room would normaly take part of that TTS command (since someone is present). That room got muted by a DnD boolean of that person since he would like to not be disturbed. The player may or may not be playing music currently.

Conclusion:
I get the volume adjusted of the players accordingly with templates, so that's ok, and then just send the command to the speakers without volume adjustments. But what I struggle with is to determine the relevant players within one chime_tts.say command. I could boyle it down to one boolean per player if the player should take part of that TTS or not. How to include this into one chime_tts.say command? Any ideas?

**Comment by nimroddolev** [comment]
Hey @andyfrei.

> I would like to select player dynamically according to different states of other sensors/templates/booleans

After reviewing the conditions you described in the **Additional context** section of your feature request: the correct way to do this (as you touched upon) is by using Jinja templating to create a dynamic list of `media_player` entities based on the range of sensor state/attribute values you described, and then pass that list to Chime TTS.

Chime TTS does not have access to additional entity state/attribute values that standard templating can make use of. If the templating you have is unreliable, then I would guess that either the template is incorrect somehow, or the integrations/platforms of the various entities you are using are themselves unreliable - but this is outside of the scope of Chime TTS.

>  Bonus: Different volume levels per player would be "the cream"

This can already be done by adding your list of desired `media_player` volume levels in the `volume_level` parameter.
Please [see the  `volume_level` documentation](https://nimroddolev.github.io/chime_tts/docs/documentation/actions/say-action/parameters#advanced-usage) for more details.

Once you have a reliable template for returning the relevant `media_players` you can iterate over them and assign the relevant `volume_level` as necessary.

**Comment by andyfrei** [comment]
Hey  ***@***.***> @nimroddolev/chime_tts

 

Thank you for your quick reply!

 

It seems since HA 2024.10 I have an issue with Chime_TTS only playing on the first player of the list, before I had a (at least until then) working jinja file.

May this be related to the new HA Version (currently on Core 2024.10.4)?

 

Regarding the Volume_Level: haven’t know that, that’s great! Can you also include templating eg use a template to determine which volume level to use per player?

**Comment by nimroddolev** [comment]
Hi @andyfrei.

> I have an issue with Chime_TTS only playing on the first player of the list

I don't think there have been any changes in Chime TTS which would have resulted in a change here...it's possible it's a Home Assistant bug, but before I run their good name through the mud, can you please [enable debug log messages](https://nimroddolev.github.io/chime_tts/docs/support#debug-logging) and send me the log messages so that I might be able to understand better what might be causing this issue?

> Can you also include templating eg use a template to determine which volume level to use per player?

I believe a template should work here providing that it converts to a dictionary with the `media_player`'s entity IDs as the key names, and the desired volume levels as the values, eg:

```
{
  "media_player.kitchen": 1.00,
  "media_player.bedroom": 0.45,
  "media_player.living_room": 0.75,
  "media_player.study": 0.5
}
```

**Comment by andyfrei** [comment]
Hi  ***@***.***> @nimroddolev/chime_tts

 

Will do, but before could you please confirm that this output format of the imported jinja-file looks correct:

 

['media_player.buro', 'media_player.wohnzimmer']

 

Or do I have a formatting error in the list generated by the file?

 

BR Andy

**Comment by andyfrei** [comment]
Hi @nimroddolev 

Ok, found the following:
1. The jinja templates do not get reloaded in HA unless I manually reload them with "homeassistant.reload_custom_templates"
2. Chime_TTS only plays to the first player in the list and ignores the rest of the jinja output

What I've done while log/debug:
1. played chime_tts to ['media_player.kuche', 'media_player.buro', 'media_player.wohnzimmer']
   > only media_player.kuche was playing
2. used a boolean to prohibit media_player.kuche from playing
3. played chime_tts, should be to ['media_player.buro', 'media_player.wohnzimmer']
   > still and only media_player.kuche was playing
4. used the service homeassistant.reload_custom_templates
5. played chime_tts, should be to ['media_player.buro', 'media_player.wohnzimmer']
   > now only media_player.buro was playing
6. revoked the boolean again so media_player.kuche was allowed again to play
7. played chime_tts should be to ['media_player.kuche', 'media_player.buro', 'media_player.wohnzimmer']
   > still and only media_player.buro was playing
8. used the service homeassistant.reload_custom_templates
9. played chime_tts, should be to ['media_player.kuche', 'media_player.buro', 'media_player.wohnzimmer']
   > now again and only media_player.kuchewas playing

Unless I'm doing something wrong I believe
1. there is a Chime or HA bug preventing Chime_TTS to use more than one player
2. there is also an HA bug preventing to use the actual jinja output unless the custom templates are reloaded manually (even after five minutes tested)

Please find attached the requested LOG for chime_tts, the full log and the jinja-file  (renamed for upload from .jinja to .txt, which resides in the custom templates folder) I'm using to determine permitted players 

[CHIMELOG home-assistant_2024-10-29T09-40-11.374Z.log](https://github.com/user-attachments/files/17554738/CHIMELOG.home-assistant_2024-10-29T09-40-11.374Z.log)
[FULLLOG home-assistant_2024-10-29T09-41-06.538Z.log](https://github.com/user-attachments/files/17554741/FULLLOG.home-assistant_2024-10-29T09-41-06.538Z.log)
[tts_all_useful.txt](https://github.com/user-attachments/files/17554750/tts_all_useful.txt)

**Comment by andyfrei** [comment]
I've also opened an issue with HA core regarding the custom_template not getting reloaded unless manually service call, in hope of not annoying anyone: https://github.com/home-assistant/core/issues/129399

**Comment by jesse-kaufman** [comment]
Playing to multiple players works for me (as long as they're all Alexa speakers, in my case). 

You could always use jinja in the actual call or a template sensor, rather than using a custom template. Custom templates have to be manually reloaded, whereas the others don't. In my case, I use Node-RED to build the array of players before sending the call to Chime TTS

**Comment by andyfrei** [comment]
Hi Jesse

 

Thanks for the hint with using a template sensor instead of jinja custom templates. Didn’t know that and it works definitely better 😉

 

But other stuff is getting weird now:

When I test to send a TTS via the developer tools it all works as expected and all of the appointed players speak the message as intended. It both works, with the template sensor aswell as with the jinja file output.

 

But when I use it in my automation & script only the first of the players in the list speaks the message.

 

Any idea why it was working before with 2024.9 and now with 2024.10.4 not anymore with the same automation/script?

 

By the way: using Sonos speakers…

**Comment by andyfrei** [comment]
Hi @nimroddolev 

I dont get it, hope you see someting in here.
Attached is a full log aswell as a chime_tts only log
I get chime_tts to work as expected when called from the developer tools directly but somehow only the first player in the list (generated now from a template sensor) when used with a script.

Would appreciate it very much if you could have a look and maybe point me into the right direction, been searching for hours now and don't see the tree in the woods anymore 🤣😫

[chime home-assistant_2024-10-30T08-43-39.775Z.log](https://github.com/user-attachments/files/17568648/chime.home-assistant_2024-10-30T08-43-39.775Z.log)

[home-assistant_2024-10-30T08-43-03.990Z.log](https://github.com/user-attachments/files/17568651/home-assistant_2024-10-30T08-43-03.990Z.log)

**Comment by andyfrei** [comment]
Ah, got it. If I get rid of the two
- join_players: true
- unjoin_players: true
I'm back up and running!

Still weird though. But nevermind, I'm happy again! ;-)

**Comment by nimroddolev** [comment]
Hey @andyfrei, i'm glad you were able to resolve the issues. I am closing the issue,
