### ISSUE TITLE
sry, no help needed.

### ISSUE THREAD

**Issue by labaland** [nimroddolev/chime_tts#22]
Ops, nevemind, missed one step in the guide. Sorry.

**Comment by nimroddolev** [comment]
Hi @labaland, happy to hear you managed 👍

**Comment by labaland** [comment]
> Hi @labaland, happy to hear you managed 👍

:)
But i have one problem now. I try this service call:

```
service: chime_tts.say
target:
  entity_id:
    - media_player.master
data:
  tts_platform: cloud
  message: Hello world
  volume_level: 0.5
  chime_path: custom_components/chime_tts/mp3s/drumroll.mp3
```
I can hear the speaker change volume, but it wont speak tss och play the mp3 file. Same with only tts. Tested on two kinds of google  speakers :P

**Comment by nimroddolev** [comment]
If you only hear the chime MP3 file (drumroll.mp3) then the issue is likely with your TTS platform. Chime TTS does not set up the TTS platform for you, you need to do that separately.

In your YAML example you set `tts_platform` to `cloud` "Nabu Casa Cloud TTS"). This TTS platform is part of the Nabu Casa subscription, so it might be the case that you don't have a valid subscription and therefore don't have access to it.

You can start a free trial, or you can use another TTS platform like [Google Translate](https://www.home-assistant.io/integrations/google_translate/) for free, or take a look at [any of the other TTS platform integrations](https://www.home-assistant.io/integrations/#text-to-speech) you can add to your Home Assistant instance.

**Comment by nimroddolev** [comment]
It would be helpful if you could turn on debug logging so that I can get a clearer idea of what's going on:

1. Turn on debug logging:
```
service: logger.set_level
data:
  custom_components.chime_tts: debug
```

2. Call the service `chime_tts.say` again.

3. Check your log messages in Home Assistant:
`https://{YOUR_HOME_ASSISTANT_ADDRESS}:8123/config/logs?filter=chime_tts`
and click `LOAD FULL LOGS`

**Comment by labaland** [comment]
Hi! Hi have paid working nabu casa. Also tried woth google_translate:

here are the log:  https://pastebin.com/kfDYBJf3

:)

**Comment by labaland** [comment]
> It would be helpful if you could turn on debug logging so that I can get a clearer idea of what's going on:
> 
> 1. Turn on debug logging:
> 
> ```
> service: logger.set_level
> data:
>   custom_components.chime_tts: debug
> ```
> 
> 2. Call the service `chime_tts.say` again.
> 3. Check your log messages in Home Assistant:
>    `https://{YOUR_HOME_ASSISTANT_ADDRESS}:8123/config/logs?filter=chime_tts`
>    and click `LOAD FULL LOGS`

Hi! Hi have paid working nabu casa. Also tried woth google_translate:

here are the log: https://pastebin.com/kfDYBJf3

:)

**Comment by nimroddolev** [comment]
Thanks for the debug logs 👍 

It seems that the audio is created successfully:
```
2023-09-26 13:38:00.543 DEBUG (MainThread) [custom_components.chime_tts] - File saved successfully
2023-09-26 13:38:00.543 DEBUG (MainThread) [custom_components.chime_tts] - audio_dict = {'audio_path': '/media/sounds/temp/chime_tts/px2t8khd.mp3', 'audio_duration': 1.824}
```

...but HA has an issue with themp3 output's file path:
```
2023-09-26 13:38:00.549 WARNING (MainThread) [custom_components.chime_tts] An error occurred: Unknown source directory.
```

My guess is that your HA instance does not have access to the `media` folder. Please check if you see the line `media_source:` in your `configurations.yaml file`, and if not: add it, restart and then try the `chime_tts.say` service again.

**Comment by labaland** [comment]
<img width="1046" alt="image" src="https://github.com/nimroddolev/chime_tts/assets/20958435/8262a4b9-5a37-448f-a328-e8ccee3ac260">

**Comment by nimroddolev** [comment]
DId you check whether you have this line in your `configurations.yaml` file?
```
media_source:
```
For example:
```
homeassistant:
  media_dirs:
    f1: "/f1"
    wallpapers: "/wallpapers"

media_source:

default_config:
...
```

**Comment by labaland** [comment]
> DId you check whether you have this line in your `configurations.yaml` file?
> 
> ```
> media_source:
> ```
> 
> For example:
> 
> ```
> homeassistant:
>   media_dirs:
>     f1: "/f1"
>     wallpapers: "/wallpapers"
> 
> media_source:
> 
> default_config:
> ...
> ```

Yes i have them both, hmmm :/

**Comment by labaland** [comment]
It starts the cast on the google home mini but no tts. and this message in log: An error occurred: Unknown source directory..
wierd :P

**Comment by labaland** [comment]
> DId you check whether you have this line in your `configurations.yaml` file?
> 
> ```
> media_source:
> ```
> 
> For example:
> 
> ```
> homeassistant:
>   media_dirs:
>     f1: "/f1"
>     wallpapers: "/wallpapers"
> 
> media_source:
> 
> default_config:
> ...
> ```

Hi ! I got it to work now!
i added this line under media_dirs:    "local: /media"

```
homeassistant:
  media_dirs:
    local: /media
```
Running ha in docker on ubuntu server

**Comment by nimroddolev** [comment]
Excellent! 👍

> > DId you check whether you have this line in your `configurations.yaml` file?
> > ```
> > media_source:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For example:
> > ```
> > homeassistant:
> >   media_dirs:
> >     f1: "/f1"
> >     wallpapers: "/wallpapers"
> > 
> > media_source:
> > 
> > default_config:
> > ...
> > ```
> 
> Hi ! I got it to work now! i added this line under media_dirs: "local: /media"
> 
> ```
> homeassistant:
>   media_dirs:
>     local: /media
> ```
> 
> Running ha in docker on ubuntu server

Excellent! 👍
