### ISSUE TITLE
self.config_entry = config_entry. This will stop working in Home Assistant 2025.12

### ISSUE THREAD

**Issue by chris4prez** [nimroddolev/chime_tts#223]
## System Information

version | core-2024.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.51-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1475
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 9, 2025 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-12.ui.nabu.casa
certificate_status | ready
instance_id | f2554fa2f6c8451b8966e5359b57c925
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 457.7 GB
disk_used | 14.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (19.0.0), Studio Code Server (5.17.3), Duck DNS (1.18.0), Let's Encrypt (5.2.7), NGINX Home Assistant SSL proxy (3.11.1), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 22, 2024 at 7:00 PM
-- | --
current_recorder_run | December 7, 2024 at 1:52 PM
estimated_db_size | 46.10 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Detected that custom integration 'chime_tts' sets option flow config_entry explicitly, which is deprecated at custom_components/chime_tts/config_flow.py, line 81: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/nimroddolev/chime_tts/issues 

### Reproduction steps

Launch a playback of chimetts as of 2024.12.1 and will see this error in the logs.

### Debug logs

```text
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 1:56:12 PM (1 occurrences)
Last logged: 1:56:12 PM

Detected that custom integration 'chime_tts' sets option flow config_entry explicitly, which is deprecated at custom_components/chime_tts/config_flow.py, line 81: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/nimroddolev/chime_tts/issues
```

**Comment by nimroddolev** [comment]
Thank you. This issue will be addressed in the next version
