### ISSUE TITLE
Improve Security of Publicly Accessible Temporary File Names

### ISSUE THREAD

**Issue by d1egoaz** [nimroddolev/chime_tts#226]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The current naming convention for temporary files uses short, alphanumeric filenames (e.g., 260b9q47.mp3). These short names are vulnerable to enumeration and brute-force attacks, especially when files are publicly accessible.

For example the files generated by HA in the `/config/tts/` folder look like this:
```
01f3c53437ec8dbc7244fe3e4c3eef48bfec0290_es_3f35d0ab30_tts.openai_tts_shimmer_say.wav
04986bf3f854f870c64484694a67d6b9a448a042_en_-_tts.openai_tts_shimmer_say.mp3
04fb45e6d0def36787af5b57b627728038e046a7_es_3f35d0ab30_tts.openai_tts_shimmer_say.wav
061ee37f3b50a9b42dc3987c18b7b8d1311bc8ea_en_-_tts.openai_tts_shimmer_say.mp3
```

### Describe the solution you'd like

Incorporate more secure identifiers (e.g., SHA256 hashes, UUIDs).

Optionally include additional entropy (e.g., timestamps or random salts).

### Describe alternatives you've considered

n/a

### Additional context

Thanks for this amazing integration!

**Comment by nimroddolev** [comment]
Thanks for your suggestion. I agree that it's a good idea. I will include it in the next release
