### ISSUE TITLE
Not able to get this to work.

### ISSUE THREAD

**Issue by sheminasalam** [nimroddolev/chime_tts#26]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not working. I am sharing the logs from the integration.

### Describe the solution you'd like

no

### Describe alternatives you've considered

no

### Additional context

This error originated from a custom integration.

Logger: custom_components.chime_tts
Source: custom_components/chime_tts/__init__.py:949
Integration: Chime TTS (documentation, issues)
First occurred: 9:33:45 AM (1 occurrences)
Last logged: 9:33:45 AM

An error occurred: Unknown source directory.

**Comment by nimroddolev** [comment]
Hi @sheminasalam.

The issue might be that your Home Assistance instance cannot access the media folder.

To see if this is the cause, please add the following YAML to your configurations.yaml file:
```
homeassistant:
  media_dirs:
    local: /media
```

and then restart your Home Assistant.

It could be helpful to enable debug logging for Chime TTS before calling the service to get a full picture of what's going on:

1. Go to the `Developer tools` menu item, and then select the `SERVICES` tab

2. Enable debug logging by calling this service:

```
service: logger.set_level
data:
  custom_components.chime_tts: debug
```

4. With debugging now enabled, run the `chime_tts.say` service.

5. Navigate to your Home Assistant log: _https://**[YOUR_HA_INSTANCE]**:8123/config/logs?filter=chime_tts_

7. Press the `LOAD FULL LOGS` button.

**Comment by sheminasalam** [comment]
It worked with adding the directory. thanks. appreciate the good work man.
