### ISSUE TITLE
The TTS stopped working, but the Mediafile still plays

### ISSUE THREAD

**Issue by ChristopherSathen** [nimroddolev/chime_tts#37]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

As of today I get this error:

This error originated from a custom integration.
Logger: custom_components.chime_tts
Source: custom_components/chime_tts/__init__.py:543
Integration: Chime TTS (documentation, issues)
First occurred: 11:07:06 AM (10 occurrences)
Last logged: 3:30:00 PM
- Error calling tts.media_source.generate_media_source_id: Invalid variable type: value should be str, int or float, got False of type <class 'bool'>

It's been working fine sice I installed the add-on a few weeks ago. The mediafile plays but there is no TTS. I've checked that a manual TTS via the UI works via Media/TTS/Cloud. I use the "Nabu Casa Cloud".

### Describe the solution you'd like

I want my messages read out again.

### Describe alternatives you've considered

I'd hate to revert to the old way with the 3 step config. Media ->Wait-time -> TTS.

### Additional context

None

**Comment by nimroddolev** [comment]
Hi @ChristopherSathen, i'm sorry to hear you've run into this issue.

Can you please provide me with (1) the full YAML you used when calling the `chime_tts.say` service, and (2) the full debug logs for the service call?

To enable debug logging:

1. Enable debug logging for Chime TTS:
```
service: logger.set_level
data:
  custom_components.chime_tts: debug
```

2. Call the `chime_tts.say` service again.

3. Check your log messages in Home Assistant:
```
https://{YOUR_HOME_ASSISTANT_ADDRESS}:8123/config/logs?filter=chime_tts
```

4. Click `LOAD FULL LOGS`

**Comment by ChristopherSathen** [comment]
Sure, here is one automation (but it applies to over 50 of them)

alias: "Klocka: (TTS)"
description: ""
trigger:
  - platform: time_pattern
    minutes: /30
condition:
  - condition: state
    entity_id: input_boolean.nattlage
    state: "off"
action:
  - service: chime_tts.say
    data:
      chime_path: media/airport_announcement.mp3
      tts_playback_speed: 100
      tts_platform: cloud
      cache: true
      gender: male
      message: |
        {% if now().minute == 0 %}
          {{ now().hour }}
        {% else %}
          {{ now().hour }} och {{ now().minute }}
        {% endif %}
    target:
      entity_id: media_player.hushogtalaren
mode: single

And the Log is attatched.
[chime_tts_log.txt](https://github.com/nimroddolev/chime_tts/files/13190863/chime_tts_log.txt)

**Comment by pepe59** [comment]
Same here
Tato chyba pochází z vlastní integrace.

```
Logger: custom_components.chime_tts
Source: custom_components/chime_tts/__init__.py:646
Integration: Chime TTS (documentation, issues)
First occurred: 10:07:32 (1 occurrences)
Last logged: 10:07:32

Unable to generate TTS audio
```
```
Tato chyba pochází z vlastní integrace.

Logger: custom_components.chime_tts
Source: custom_components/chime_tts/__init__.py:543
Integration: Chime TTS (documentation, issues)
First occurred: 10:07:32 (1 occurrences)
Last logged: 10:07:32

- Error calling tts.media_source.generate_media_source_id: Invalid variable type: value should be str, int or float, got False of type <class 'bool'>
```

**Comment by nimroddolev** [comment]
Hi @ChristopherSathen and @pepe59.

I released a beta version v0.7.5-beta1, which I hope addresses this issue.
Please upgrade to the beta when you have a chance and let me know if the issue is resolved for you.

To install the new version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option (wait a moment for it to load)
1. Select version `v0.7.5-beta1` from the updated version drop-down list and then select `DOWNLOAD`
1. Restart Home Assistant

**Comment by ChristopherSathen** [comment]
That worked like a charm. Thank you.

**Comment by nimroddolev** [comment]
Excellent, thanks for the feedback. I will push out the release.
