### ISSUE TITLE
TTS not playing.

### ISSUE THREAD

**Issue by troy-lim** [nimroddolev/chime_tts#47]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It only plays the opening and closing chimes without the message.
Here is the code that I use:

`service: chime_tts.say
data:
  chime_path: mp3_path_placeholder-classical
  end_chime_path: mp3_path_placeholder-classical
  delay: 450
  final_delay: 0
  message: Test announcement.
  tts_platform: google_translate
  tts_playback_speed: 100
  volume_level: 1
  language: en
  tld: com
target:
  entity_id: media_player.master_bedroom_speaker`

Here is the full log:
`2023-11-14 12:39:43.022 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration chime_tts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-14 12:44:11.271 WARNING (MainThread) [custom_components.chime_tts] - Error calling tts.media_source.generate_media_source_id: Invalid TTS provider selected
2023-11-14 12:44:11.272 WARNING (MainThread) [custom_components.chime_tts] Unable to generate TTS audio`

Home Assistant
Core - 2023.11.2
Supervisor - 2023.11.0
Operating System - 11.1
Frontend - 20231030.2
Chime TTS Version - v0.8.0
### Describe the solution you'd like

I would like to hear both the chimes and the message together. 

### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by nimroddolev** [comment]
Hi @troy-lim ,

Chime TTS does not add all TTS platforms to your Home Assistance instance, you need to add them separately.

To use the Google Translate TTS platform, add the following to your configuration.yaml file:

```
tts:
  - platform: google_translate
    service_name: google_say
```

**Comment by troy-lim** [comment]
Thank you so much! It worked like a charm.

**Comment by troy-lim** [comment]
That was quick! 
Thank you so much! It worked like a charm.
