### ISSUE TITLE
Allow Repeating Messages

### ISSUE THREAD

**Issue by tjw1184** [nimroddolev/chime_tts#64]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'd like to be able to repeat the message n times (1..n), especially for important messages to make sure they get heard

### Describe the solution you'd like

Two new variable
- Message Repeat Counter (minimum 1, maximum 50?)
- Message Delay ms, amount of delay between messages, default 500 or 1000 ms
- Possible Optional third to allow chime to play between messages if desired 

When generating mp3, if counter > 1, add message delay and message n-1 times after the first message.  If option to put chime between messages was implemented, could do if counter > 1, add existing chime delay then chime and existing chime delay and message n-1 times after the first message

### Describe alternatives you've considered

Currently script n times in loop, have issues with clipping\skipping and delay issues

### Additional context

n\a

**Comment by nimroddolev** [comment]
Hi @tjw1184. I'm sorry you're having issues.
Can you please send me a YAML example of repeated messages which aren't working as you expect?
I plan to implement a new feature which will also support what you've described - hopefully in a week or two.

**Comment by nimroddolev** [comment]
Hi @tjw1184, I just released a new version of Chime TTS, v0.11.0, which allows for "message segments" to be used. The functionality adde with this new feature should fulfill your feature request. Please[ review the documentation](https://github.com/nimroddolev/chime_tts/wiki/chime_tts.say/#advanced-usage-segment-sequences) and try it for yourself, and let me know if there's anything else you would like to see implemented.

Thank you.

**Comment by nimroddolev** [comment]
I am closing this issue. If you are still having issues please reopen.
Thank you.
