### ISSUE TITLE
Help with Custom sounds

### ISSUE THREAD

**Issue by Whizzykid** [nimroddolev/chime_tts#67]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm trying to understand how to use custom sounds for the chime but I'm a novice and I just don't know how to create the correct file path. I keep getting this 'Custom 1' file path invalid

A full walkthrough would be very helpful

### Describe the solution you'd like

to be able to add custom sounds for the chime

### Describe alternatives you've considered

.

### Additional context

.

**Comment by nimroddolev** [comment]
Hey @Whizzykid, happy to help.

First off, make sure to [review the documentation](https://github.com/nimroddolev/chime_tts/wiki/chime_tts.say#3-custom-chime-slots-for-the-chime-list-ui) for how to set the custom paths.

It makes sense to use a file from your media library, so make sure to upload it there.
Depending on your setup you need to work out the path to your media library's folder. Assuming you have a regular Home Assistant setup, the media folder should be located in at the root directory, so: `/media`.

If you have a file "custom_chime_file.mp3" in your media library, inside a subfolder "sounds", then then path would be: `/media/sounds/custom_chime_file.mp3`

**Comment by Whizzykid** [comment]
Thank you for the link to the WIki, totally missed that! Got it working right away! Thanks

**Comment by nimroddolev** [comment]
Ah wonderful! Let me know if there's anything else 👍

**Comment by Whizzykid** [comment]
It's nothing urgent, but I've noticed that if I wanted to play just a custom chime (with no TTS) I get 'I'm struggling to connect to simon says" (or something similar to that.

If I use any of the predefined chimes they work 100% of the time. It's no big deal, but might be worth having a look at

**Comment by nimroddolev** [comment]
It could be your custom chime isn’t “Alexa-friendly”. You should set the `audio_conversion` parameter to `Alexa`.

More details in [the documentation](https://github.com/nimroddolev/chime_tts/wiki/chime_tts.say_url#alexa-speakers).
