### ISSUE TITLE
Add support for custom TTS agent

### ISSUE THREAD

**Issue by aviadlevy** [nimroddolev/chime_tts#77]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I want to use the `chime_tts.say` with custom tts service, and not one of the provided tts platform

### Describe alternatives you've considered

My alternative is using only one of the provided TTS platforms instead of the one I'm currently using

### Additional context

No

**Comment by nimroddolev** [comment]
Hi @aviadlevy,

You can do this by setting the `tts_platform` parameter value to another TTS platform you have installed on your Home Assistant instance.

**Comment by aviadlevy** [comment]
Wow! I guess I somehow missed that from the documentation.

Thanks for the quick response

**Comment by nimroddolev** [comment]
It wasn't explained in the documentation so it's not your fault for not knowing.
Thank you for raising the issue, I'll add a comment to make it clearer 👍
