### ISSUE TITLE
Repository issue templates not working

### ISSUE THREAD

**Issue by disconn3ct** [nimroddolev/chime_tts#87]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

There are two templates in .github for bugs. This stops github from showing the template. Only 'feature request' shows.

### Describe the solution you'd like

Ability to open anything other than a feature request

### Describe alternatives you've considered

Putting bug reports into the feature request template

### Additional context

why is this field mandatory?

**Comment by nimroddolev** [comment]
Thanks for raising the issue. It is now resolved.
