### ISSUE TITLE
Default Settings

### ISSUE THREAD

**Issue by JonLaliberte** [nimroddolev/chime_tts#92]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I had a problem recently where ChimeTTS was playing a chime, then didn't speak anything. The problem ending up being that I hadn't set a TTS Platform.

This happened because I was using a template in the message, so when I entered that in, it replaced the the UI view with a YAML view, and so I simply forgot to set it.

### Describe the solution you'd like

I think it would be good to have some default settings for the integration. For example, TTS platform. Maybe it would make sense for other settings to be defaults as well. The platform though may be a good start.

### Describe alternatives you've considered

In the future, I probably won't forget to specify it.

**Comment by nimroddolev** [comment]
Hi @JonLaliberte, thanks for the suggestion. 

Setting a default TTS platform will only work in cases where a user has at least one platform configured - but I agree that it makes sense to have a default fallback.

**Comment by uli-rpi** [comment]
@JonLaliberte 

I solved this by calling chime tts from my own script and passing the desired parameters to the script. For the parameters that are relevant to me, I have stored default values ​​in the script, which should be used if a parameter is empty or if the default value is desired

**Comment by nimroddolev** [comment]
I have added support for setting default ‘tts_platform` and default `offset` values via the configuration.

Feel free to reopen this issue if you would like to see any other related changes 👍
