### ISSUE TITLE
Pause/resume Spotify media_player before/after Chime TTS notification

### ISSUE THREAD

**Issue by nimroddolev** [nimroddolev/chime_tts#93]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

This feature request is based on the [comment](https://github.com/nimroddolev/chime_tts/issues/90#issuecomment-1954644468) made by @dbullendsl.

When the `announce` parameter is enabled, Spotify media_players paused before Chime TTS notifications, however they are not resumed once the notification ends.

Spotify media_players can only play audio from Spotify and cannot play arbitrary files (neither local files nor remote URLs) - so they cannot currently be used as a media_player for Chime TTS notification playback. However, it would be useful to have them be paused/resume before/after Chime TTS notification playback.

My idea is to include them in the list of target media_players sent to the `chime_tts.say` service, and have Chime TTS identify them as Spotify media_players and handle the pause/resume (when `announce` is true).
### Describe the solution you'd like

Spotify media_players should automatically resume playback once the notification from Chime TTS is complete.

**Comment by DanDixon** [comment]
After using chime_tts.say_url to generate the audio file I turn down the volume on my music (actually fade it over 1 second with another script) and then play the file, fading the music back up after the playback is complete.

That said, I play all of my voice notifications through Google minis and all of my music via Google Chromecast audios, so they are separate devices.

**Comment by nimroddolev** [comment]
You should already be able to do this in `chime_tts.say` by setting `announce: true`.
